---
title: "Tutorial: R Basic"
---
**Downloads**: [R][R] and [RStudio][RS]

# Why R?

[What is R?][Rwhat]

Essentially, R is a language that was made to handle complex statistics, working with numerical matrices and data-frames. The strength of R over other languages lies in its statistics, linear algebra, and especially ability to make graphs and figures from data.

[Rwhat]:https://www.r-project.org/about.html

### But I always hear about how great Python is.

Yes, [Python][Py] is a beautiful language that strikes an amazing balance between syntax and power. With the frequent release of new packages for both R and Python the overlap in function is becoming greater. However, for now R still has the upper-hand when it comes to math, statistics, and graphs.

> I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times. - Bruce Lee

There is a lot of truth to this. My recommendation is to find which is most useful and spend time mastering that one. For a lot of scientists, this tends to be R. But there is certainly a lot of use in being familiar and comfortable with multiple languages.

[Py]:https://www.python.org/

# Inital Setup

To work through this tutorial you will need to download and install the latest version of [R][R] from the [CRAN][R] website.

Additionally, but not necessary, [RStudio][RS] is a nice program that runs R and makes many things easier for users, particularly saving and opening files and figures.

And now we are ready to get started!

[R]:https://mirror.las.iastate.edu/CRAN/
[RS]:https://www.rstudio.com/products/rstudio/download/#download

# [Exercise 1][Ex1]

**Getting Started** - Opening R and familiarizing with the basics of how it works.

  + [**First Time In R**](exercise_1.html#first_time_in_r)
  + [**Whitespace**](exercise_1.html#whitespace)
  + [**Order of Operations**](exercise_1.html#order_of_operations)
  + [**Scientific Notation**](exercise_1.html#scientific_notation)
  + [**Functions**](exercise_1.html#functions)
  + [**Variables**](exercise_1.html#variables)
  + [**Operators**](exercise_1.html#operators)
  + [**Packages**](exercise_1.html#packages)

# [Exercise 2][Ex2]

**Data-Structures** - 

# [Exercise 3][Ex3]

**Writing Scripts** - 

# [Exercise 4][Ex4]

**Processing Our Data** - 

[Ex1]:exercise_1.html
[Ex2]:exercise_2.html
[Ex3]:exercise_3.html
[Ex4]:exercise_4.html
# Questions

If you have any questions, feel free to contact me by e-mail at <sdsmith@iastate.edu>

**Disclaimer:** There are peple far, far more knowledgeable about R and how it works than myself. There are very few questions that I have had that I could not find the answer to explained by an expert on [stackoverflow][stack] or similar sites.

[stack]:https://stackoverflow.com/




